version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox
jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/api/app
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox
  test_and_upload_classifier_model:
    <<: *defaults
    working_directory: ~/project/api/app
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Test the model
          command: |
            tox
tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 2
  section_07:
    jobs:
      - test_app
      # upload after git tags are created
      - test_and_upload_classifier_model:
          <<: *tags_only
